Repository potatoeggy/connectfour, pull requests merged in 2020-06, with the labels that each got.

#24 Rearrange functions to make slaves obey their master, initial player v player support
  src/GameWindow.java
  src/MainWindow.java
  src/OptionsMenu.java
Labels: frontend, integration

#28 timer: make opposing player win when timer runs out
  src/GameWindow.java
  src/MainWindow.java
Labels: frontend

#33 AI work to make AI and gooey interactable
  src/AI.java
Labels: ai, frontend

#32 Alpha beta pruning
  src/AI.java
  src/AITest.java
  src/Board.java
Labels: ai, backend, enhancement

#37 Improve responsiveness when playing against computers
  src/AI.java
  src/GameWindow.java
  src/MainWindow.java
  src/OptionsMenu.java
Labels: frontend

#34 Frontend work to allow interaction between ai and gooey
  src/AI.java
  src/AITest.java
  src/Board.java
  src/GameWindow.java
  src/MainWindow.java
  src/OptionsMenu.java
Labels: frontend, integration

#40 Frontend Javadoc
  src/GameWindow.java
  src/MainMenu.java
  src/MainWindow.java
  src/NewGameMenu.java
  src/OptionsMenu.java
Labels: documentation, frontend

#45 Integrate save code with graphical code
  .gitignore
  src/AI.java
  src/GameWindow.java
  src/MainMenu.java
  src/MainWindow.java
  src/OptionsMenu.java
Labels: backend, integration

#44 Implemented game saving and retrieval in MainWindow.java
  .gitignore
  src/AI.java
  src/GameWindow.java
  src/MainMenu.java
  src/MainWindow.java
  src/OptionsMenu.java
Labels: backend, enhancement, frontend

#43 Improved Win checking and re-enabled alpha beta pruning
  src/AI.java
  src/AITest.java
Labels: ai, backend, enhancement

#48 ai: make sure easy mode doesn't choose a full column
  src/AI.java
Labels: ai, bug

#49 Add support for --verbose
  src/GameWindow.java
  src/MainWindow.java
Labels: backend, enhancement

#51 gamewindow: fix border flickers when moving mouse around
  src/GameWindow.java
Labels: frontend

#53 Changed AI.minMax return value and disabled A-B pruning
  src/AI.java
  src/NewGameMenu.java
Labels: ai, backend, enhancement
