Repository potatoeggy/connectfour, pull requests merged in 2020-05, with the labels that each got.

#1 Main menu initial implementation
  src/ConnectFour.java
  src/MainMenu.java
  src/MainWindow.java
  src/NewGameMenu.java
  src/OptionsMenu.java
Labels: frontend

#6 Options menu initial implementation
  src/MainMenu.java
  src/MainWindow.java
  src/NewGameMenu.java
  src/OptionsMenu.java
Labels: frontend

#14 Ai debugging
  src/AI.java
  src/Board.java
  src/test.java
Labels: ai, backend

#17 Board initial graphical implementation
  src/GameWindow.java
  src/MainWindow.java
  src/NewGameMenu.java
  src/OptionsMenu.java
  src/resources/arrow.png
Labels: frontend

#19 board: validate input from nextEmpty
  src/Board.java
Labels: backend

#22 Initial integration of frontend with backend
  src/Board.java
  src/GameWindow.java
  src/MainWindow.java
  src/resources/red.png
  src/resources/yellow.png
Labels: integration
